# Generated by Django 5.2.17 on 2026-08-19 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING_APPROVAL', 'Pending Approval'), ('COMPLETED', 'Completed')], default='OPEN', max_length=20)),
                ('contribution_amount', models.PositiveIntegerField()),
                ('deadline', models.DateTimeField()),
                ('payout_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='circles.circle')),
                ('payout_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds_as_recipient', to='circles.circlemember')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('penalty', models.PositiveIntegerField(default=0)),
                ('total_paid', models.PositiveIntegerField()),
                ('is_late', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='circles.circlemember')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='rounds.round')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='round',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('circle',), name='unique_open_round_per_circle'),
        ),
        migrations.AddConstraint(
            model_name='contribution',
            constraint=models.UniqueConstraint(fields=('round', 'member'), name='unique_contribution_per_round_member'),
        ),
    ]
