# Generated by Django 5.2.17 on 2026-08-19 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='circle',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_circles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='circlemember',
            name='circle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='circles.circle'),
        ),
        migrations.AddField(
            model_name='circlemember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circle_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='circlemember',
            constraint=models.UniqueConstraint(fields=('circle', 'user'), name='unique_circle_user'),
        ),
        migrations.AddConstraint(
            model_name='circlemember',
            constraint=models.UniqueConstraint(fields=('circle', 'position'), name='unique_circle_position'),
        ),
    ]
